### ISSUE TITLE
Redirecionamento para página de erro quando usuário adiciona igrediente e não passa nenhum valor

### ISSUE THREAD

**Issue by nouoneq** [flavio-muniz/MALO---fds-2023.1#14]
![image](https://user-images.githubusercontent.com/78773314/232559251-56d9618f-cdcb-42f2-aa23-6c87af119c0c.png)

![image](https://user-images.githubusercontent.com/78773314/232553255-50d40de5-463e-4939-a011-707f55c71427.png)

**Comment by flavio-muniz** [comment]
Apesar da mensagem de erro, o prato é adicionado ao cardápio
![image](https://user-images.githubusercontent.com/116359369/232559574-aa51c0fc-e09d-4608-9721-4d2bd8fb21a6.png)

**Comment by Arrudadiego** [comment]
![image](https://github.com/flavio-muniz/MALO---fds-2023.1/assets/116604134/5b480252-caf5-413c-9080-5a7a28b07921)
Agora, quando o preço não é inserido, o prato não pode ser enviado

**Comment by Arrudadiego** [comment]
![image](https://github.com/flavio-muniz/MALO---fds-2023.1/assets/116604134/4c82008f-0063-4a0b-9743-cf305c1a09c4)
Agora, quando se tenta repetir o passo, informa que o campo é obrigatório.
